baseURL = "https://gden173.github.io/gabrieldennis/"
languageCode = "en-us"
title = "Gabriel Dennis"
theme = "ananke"

DefaultContentLanguage = "en"
SectionPagesMenu = "main"
googleAnalytics = ""
enableRobotsTXT = true



[[menu.main]]
name = "posts"
weight = 20
identifier = "posts"
url = "/posts"

[[menu.main]]
name = "resume"
weight = 20
identifier = "resume"
url="/resume"

[[menu.main]]
name = "tags"
weight = 20
identifier = "tags"
url="/tags"


[params]
commentsEnable = true

[[params.ananke_socials]]
name = "github"
url = "https://github.com/gden173"

[[params.ananke_socials]]
name = "linkedin"
url = "https://www.linkedin.com/in/gden173/"

