baseURL = "https://gabrieldennis.ml/"
languageCode = "en-us"
title = "LBFGS"
theme = "ananke"

DefaultContentLanguage = "en"
SectionPagesMenu = "main"
googleAnalytics = ""
enableRobotsTXT = true


[params]
commentsEnable = true



[[params.ananke_socials]]
name = "github"
url = "https://github.com/gden173"

[[params.ananke_socials]]
name = "linkedin"
url = "https://www.linkedin.com/in/gden173/"

